extern const GeoLayout mountain_area_1_geo[];
extern const GeoLayout mountain_area_1[];
extern const Collision mountain_area_1_collision[];
extern const MacroObject mountain_area_1_Area_Root_macro_objs[];
extern Vtx mountain_dl_cutout_mesh_vtx_0[41];
extern Gfx mountain_dl_cutout_mesh_tri_0[];
extern Vtx mountain_dl_solid_mesh_vtx_0[93];
extern Gfx mountain_dl_solid_mesh_tri_0[];
extern Vtx mountain_dl_solid_mesh_vtx_1[12];
extern Gfx mountain_dl_solid_mesh_tri_1[];
extern Vtx mountain_dl_solid_mesh_vtx_2[6];
extern Gfx mountain_dl_solid_mesh_tri_2[];
extern Vtx mountain_dl_solid_mesh_vtx_3[46];
extern Gfx mountain_dl_solid_mesh_tri_3[];
extern Vtx mountain_dl_solid_mesh_vtx_4[4];
extern Gfx mountain_dl_solid_mesh_tri_4[];
extern Vtx mountain_dl_solid_mesh_vtx_5[4];
extern Gfx mountain_dl_solid_mesh_tri_5[];
extern Vtx mountain_dl_solid_mesh_vtx_6[8];
extern Gfx mountain_dl_solid_mesh_tri_6[];
extern Vtx mountain_dl_solid_mesh_vtx_7[12];
extern Gfx mountain_dl_solid_mesh_tri_7[];
extern Vtx mountain_dl_solid_mesh_vtx_8[54];
extern Gfx mountain_dl_solid_mesh_tri_8[];
extern Vtx mountain_dl_solid_mesh_vtx_9[12];
extern Gfx mountain_dl_solid_mesh_tri_9[];
extern Vtx mountain_dl_solid_mesh_vtx_10[16];
extern Gfx mountain_dl_solid_mesh_tri_10[];
extern Vtx mountain_dl_solid_mesh_vtx_11[58];
extern Gfx mountain_dl_solid_mesh_tri_11[];
extern Vtx mountain_dl_solid_mesh_vtx_12[4];
extern Gfx mountain_dl_solid_mesh_tri_12[];
extern Vtx mountain_dl_solid_mesh_vtx_13[60];
extern Gfx mountain_dl_solid_mesh_tri_13[];
extern Vtx mountain_dl_solid_mesh_vtx_14[25];
extern Gfx mountain_dl_solid_mesh_tri_14[];
extern Vtx mountain_dl_solid_mesh_vtx_15[113];
extern Gfx mountain_dl_solid_mesh_tri_15[];
extern Vtx mountain_dl_solid_mesh_vtx_16[9];
extern Gfx mountain_dl_solid_mesh_tri_16[];
extern Vtx mountain_dl_solid_mesh_vtx_17[16];
extern Gfx mountain_dl_solid_mesh_tri_17[];
extern Vtx mountain_dl_solid_mesh_vtx_18[50];
extern Gfx mountain_dl_solid_mesh_tri_18[];
extern Vtx mountain_dl_solid_mesh_vtx_19[58];
extern Gfx mountain_dl_solid_mesh_tri_19[];
extern Vtx mountain_dl_solid_mesh_vtx_20[24];
extern Gfx mountain_dl_solid_mesh_tri_20[];
extern Vtx mountain_dl_solid_mesh_vtx_21[35];
extern Gfx mountain_dl_solid_mesh_tri_21[];

extern Gfx mountain_dl_cutout_mesh[];
extern Gfx mountain_dl_solid_mesh[];
extern Gfx mountain_dl_material_revert_render_settings[];

