#ifndef WF_HEADER_H
#define WF_HEADER_H

#include "types.h"
#include "game/moving_texture.h"

extern const GeoLayout mountain_area_1_geo[];
extern const Collision mountain_area_1[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const Collision mountain_area_1_collision[];
extern const MacroObject mountain_area_1_Area_Root_macro_objs[];
extern Vtx mountain_dl_cutout_mesh_vtx_0[40];
extern Gfx mountain_dl_cutout_mesh_tri_0[];
extern Vtx mountain_dl_non_solid_mesh_vtx_0[32];
extern Gfx mountain_dl_non_solid_mesh_tri_0[];
extern Vtx mountain_dl_non_solid_mesh_vtx_1[128];
extern Gfx mountain_dl_non_solid_mesh_tri_1[];
extern Vtx mountain_dl_objects_mesh_vtx_0[100];
extern Gfx mountain_dl_objects_mesh_tri_0[];
extern Vtx mountain_dl_objects_mesh_vtx_1[4];
extern Gfx mountain_dl_objects_mesh_tri_1[];
extern Vtx mountain_dl_objects_mesh_vtx_2[77];
extern Gfx mountain_dl_objects_mesh_tri_2[];
extern Vtx mountain_dl_objects_mesh_vtx_3[24];
extern Gfx mountain_dl_objects_mesh_tri_3[];
extern Vtx mountain_dl_objects_mesh_vtx_4[52];
extern Gfx mountain_dl_objects_mesh_tri_4[];
extern Vtx mountain_dl_objects_mesh_vtx_5[35];
extern Gfx mountain_dl_objects_mesh_tri_5[];
extern Vtx mountain_dl_solid_mesh_vtx_0[93];
extern Gfx mountain_dl_solid_mesh_tri_0[];
extern Vtx mountain_dl_solid_mesh_vtx_1[12];
extern Gfx mountain_dl_solid_mesh_tri_1[];
extern Vtx mountain_dl_solid_mesh_vtx_2[20];
extern Gfx mountain_dl_solid_mesh_tri_2[];
extern Vtx mountain_dl_solid_mesh_vtx_3[46];
extern Gfx mountain_dl_solid_mesh_tri_3[];
extern Vtx mountain_dl_solid_mesh_vtx_4[7];
extern Gfx mountain_dl_solid_mesh_tri_4[];
extern Vtx mountain_dl_solid_mesh_vtx_5[4];
extern Gfx mountain_dl_solid_mesh_tri_5[];
extern Vtx mountain_dl_solid_mesh_vtx_6[65];
extern Gfx mountain_dl_solid_mesh_tri_6[];
extern Vtx mountain_dl_solid_mesh_vtx_7[12];
extern Gfx mountain_dl_solid_mesh_tri_7[];
extern Vtx mountain_dl_solid_mesh_vtx_8[54];
extern Gfx mountain_dl_solid_mesh_tri_8[];
extern Vtx mountain_dl_solid_mesh_vtx_9[8];
extern Gfx mountain_dl_solid_mesh_tri_9[];
extern Vtx mountain_dl_solid_mesh_vtx_10[16];
extern Gfx mountain_dl_solid_mesh_tri_10[];
extern Vtx mountain_dl_solid_mesh_vtx_11[58];
extern Gfx mountain_dl_solid_mesh_tri_11[];
extern Vtx mountain_dl_solid_mesh_vtx_12[4];
extern Gfx mountain_dl_solid_mesh_tri_12[];
extern Vtx mountain_dl_solid_mesh_vtx_13[25];
extern Gfx mountain_dl_solid_mesh_tri_13[];
extern Vtx mountain_dl_solid_mesh_vtx_14[13];
extern Gfx mountain_dl_solid_mesh_tri_14[];
extern Vtx mountain_dl_solid_mesh_vtx_15[9];
extern Gfx mountain_dl_solid_mesh_tri_15[];
extern Vtx mountain_dl_solid_mesh_vtx_16[19];
extern Gfx mountain_dl_solid_mesh_tri_16[];

extern Gfx mountain_dl_cutout_mesh[];
extern Gfx mountain_dl_non_solid_mesh[];
extern Gfx mountain_dl_objects_mesh[];
extern Gfx mountain_dl_solid_mesh[];
extern Gfx mountain_dl_material_revert_render_settings[];

// geo
extern const GeoLayout wf_geo_0007E0[];
extern const GeoLayout wf_geo_000820[];
extern const GeoLayout wf_geo_000860[];
extern const GeoLayout wf_geo_000878[];
extern const GeoLayout wf_geo_000890[];
extern const GeoLayout wf_geo_0008A8[];
extern const GeoLayout wf_geo_0008E8[];
extern const GeoLayout wf_geo_000900[];
extern const GeoLayout wf_geo_000940[];
extern const GeoLayout wf_geo_000958[];
extern const GeoLayout wf_geo_0009A0[];
extern const GeoLayout wf_geo_0009B8[];
extern const GeoLayout wf_geo_0009D0[];
extern const GeoLayout wf_geo_0009E8[];
extern const GeoLayout wf_geo_000A00[];
extern const GeoLayout wf_geo_000A40[];
extern const GeoLayout wf_geo_000A58[];
extern const GeoLayout wf_geo_000A98[];
extern const GeoLayout wf_geo_000AB0[];
extern const GeoLayout wf_geo_000AC8[];
extern const GeoLayout wf_geo_000AE0[];
extern const GeoLayout wf_geo_000AF8[];
extern const GeoLayout wf_geo_000B10[];
extern const GeoLayout wf_geo_000B38[];
extern const GeoLayout wf_geo_000B60[];
extern const GeoLayout wf_geo_000B78[];
extern const GeoLayout wf_geo_000B90[];
extern const GeoLayout wf_geo_000BA8[];
extern const GeoLayout wf_geo_000BC8[];
extern const GeoLayout wf_geo_000BE0[];
extern const GeoLayout wf_geo_000BF8[];

// leveldata
extern const Gfx wf_seg7_dl_070050C8[];
extern const Gfx wf_seg7_dl_070052B8[];
extern const Gfx wf_seg7_dl_07005538[];
extern const Gfx wf_seg7_dl_07005690[];
extern const Gfx wf_seg7_dl_07005DD8[];
extern const Gfx wf_seg7_dl_07005EE8[];
extern const Gfx wf_seg7_dl_070064E8[];
extern const Gfx wf_seg7_dl_070065F8[];
extern const Gfx wf_seg7_dl_07006820[];
extern const Gfx wf_seg7_dl_07007220[];
extern const Gfx wf_seg7_dl_07007518[];
extern const Gfx wf_seg7_dl_070087B0[];
extern const Gfx wf_seg7_dl_07008FE8[];
extern const Gfx wf_seg7_dl_07009278[];
extern const Gfx wf_seg7_dl_07009780[];
extern const Gfx wf_seg7_dl_07009890[];
extern const Gfx wf_seg7_dl_07009DB0[];
extern const Gfx wf_seg7_dl_0700A170[];
extern const Gfx wf_seg7_dl_0700ABA0[];
extern const Gfx wf_seg7_dl_0700AEC8[];
extern const Gfx wf_seg7_dl_0700AFB8[];
extern const Gfx wf_seg7_dl_0700BA28[];
extern const Gfx wf_seg7_dl_0700BF50[];
extern const Gfx wf_seg7_dl_0700D028[];
extern const Gfx wf_seg7_dl_0700D300[];
extern const Gfx wf_seg7_dl_0700D708[];
extern const Gfx wf_seg7_dl_0700D9F0[];
extern const Gfx wf_seg7_dl_0700DE20[];
extern const Gfx wf_seg7_dl_0700E0F0[];
extern const Gfx wf_seg7_dl_0700E3D0[];
extern const Gfx wf_seg7_dl_0700E760[];
extern const Gfx wf_seg7_dl_0700E9B8[];
extern const Gfx wf_seg7_dl_0700EB40[];
extern const Gfx wf_seg7_dl_0700EDC0[];
extern const Gfx wf_seg7_dl_0700F018[];
extern const Gfx wf_seg7_dl_0700F1A8[];
extern const Gfx wf_seg7_dl_0700F340[];
extern const Gfx wf_seg7_dl_0700F610[];
extern const Gfx wf_seg7_dl_0700F6C0[];
extern const Gfx wf_seg7_dl_0700F7F8[];
extern const Collision wf_seg7_collision_small_bomp[];
extern const Collision wf_seg7_collision_large_bomp[];
extern const Collision wf_seg7_collision_clocklike_rotation[];
extern const Collision wf_seg7_collision_sliding_brick_platform[];
extern const Collision wf_seg7_collision_tumbling_bridge[];
extern const Collision wf_seg7_collision_trapezoid[];
extern const Collision wf_seg7_collision_platform[];
extern const Collision wf_seg7_collision_breakable_wall[];
extern const Collision wf_seg7_collision_breakable_wall_2[];
extern const Collision wf_seg7_collision_kickable_board[];
extern const Collision wf_seg7_collision_tower_door[];
extern const Collision wf_seg7_collision_rotating_platform[];
extern const Collision wf_seg7_collision_tower[];
extern const Collision wf_seg7_collision_bullet_bill_cannon[];
extern const Collision wf_seg7_collision_070102D8[];
extern const MacroObject wf_seg7_macro_objs[];
extern const struct MovtexQuadCollection wf_movtex_water[];

// script
extern const LevelScript level_wf_entry[];

#endif
