extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Vtx wf_dl_cutout_mesh_vtx_0[40];
extern Gfx wf_dl_cutout_mesh_tri_0[];
extern Vtx wf_dl_non_solid_mesh_vtx_0[32];
extern Gfx wf_dl_non_solid_mesh_tri_0[];
extern Vtx wf_dl_non_solid_mesh_vtx_1[128];
extern Gfx wf_dl_non_solid_mesh_tri_1[];
extern Vtx wf_dl_objects_mesh_vtx_0[100];
extern Gfx wf_dl_objects_mesh_tri_0[];
extern Vtx wf_dl_objects_mesh_vtx_1[4];
extern Gfx wf_dl_objects_mesh_tri_1[];
extern Vtx wf_dl_objects_mesh_vtx_2[77];
extern Gfx wf_dl_objects_mesh_tri_2[];
extern Vtx wf_dl_objects_mesh_vtx_3[24];
extern Gfx wf_dl_objects_mesh_tri_3[];
extern Vtx wf_dl_objects_mesh_vtx_4[52];
extern Gfx wf_dl_objects_mesh_tri_4[];
extern Vtx wf_dl_objects_mesh_vtx_5[35];
extern Gfx wf_dl_objects_mesh_tri_5[];
extern Vtx wf_dl_solid_mesh_vtx_0[93];
extern Gfx wf_dl_solid_mesh_tri_0[];
extern Vtx wf_dl_solid_mesh_vtx_1[12];
extern Gfx wf_dl_solid_mesh_tri_1[];
extern Vtx wf_dl_solid_mesh_vtx_2[20];
extern Gfx wf_dl_solid_mesh_tri_2[];
extern Vtx wf_dl_solid_mesh_vtx_3[46];
extern Gfx wf_dl_solid_mesh_tri_3[];
extern Vtx wf_dl_solid_mesh_vtx_4[7];
extern Gfx wf_dl_solid_mesh_tri_4[];
extern Vtx wf_dl_solid_mesh_vtx_5[4];
extern Gfx wf_dl_solid_mesh_tri_5[];
extern Vtx wf_dl_solid_mesh_vtx_6[65];
extern Gfx wf_dl_solid_mesh_tri_6[];
extern Vtx wf_dl_solid_mesh_vtx_7[12];
extern Gfx wf_dl_solid_mesh_tri_7[];
extern Vtx wf_dl_solid_mesh_vtx_8[54];
extern Gfx wf_dl_solid_mesh_tri_8[];
extern Vtx wf_dl_solid_mesh_vtx_9[8];
extern Gfx wf_dl_solid_mesh_tri_9[];
extern Vtx wf_dl_solid_mesh_vtx_10[16];
extern Gfx wf_dl_solid_mesh_tri_10[];
extern Vtx wf_dl_solid_mesh_vtx_11[58];
extern Gfx wf_dl_solid_mesh_tri_11[];
extern Vtx wf_dl_solid_mesh_vtx_12[4];
extern Gfx wf_dl_solid_mesh_tri_12[];
extern Vtx wf_dl_solid_mesh_vtx_13[25];
extern Gfx wf_dl_solid_mesh_tri_13[];
extern Vtx wf_dl_solid_mesh_vtx_14[13];
extern Gfx wf_dl_solid_mesh_tri_14[];
extern Vtx wf_dl_solid_mesh_vtx_15[9];
extern Gfx wf_dl_solid_mesh_tri_15[];
extern Vtx wf_dl_solid_mesh_vtx_16[19];
extern Gfx wf_dl_solid_mesh_tri_16[];

extern Gfx wf_dl_cutout_mesh[];
extern Gfx wf_dl_non_solid_mesh[];
extern Gfx wf_dl_objects_mesh[];
extern Gfx wf_dl_solid_mesh[];
extern Gfx wf_dl_material_revert_render_settings[];

