extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_Area_Root_macro_objs[];
extern Vtx lll_dl_skinned_mesh_vtx_0[44];
extern Gfx lll_dl_skinned_mesh_tri_0[];
extern Vtx lll_dl_skinned_mesh_vtx_1[4];
extern Gfx lll_dl_skinned_mesh_tri_1[];
extern Vtx lll_dl_skinned_mesh_vtx_2[300];
extern Gfx lll_dl_skinned_mesh_tri_2[];
extern Vtx lll_dl_skinned_mesh_vtx_3[8];
extern Gfx lll_dl_skinned_mesh_tri_3[];
extern Vtx lll_dl_skinned_mesh_vtx_4[27];
extern Gfx lll_dl_skinned_mesh_tri_4[];
extern Vtx lll_dl_skinned_mesh_vtx_5[32];
extern Gfx lll_dl_skinned_mesh_tri_5[];
extern Vtx lll_dl_skinned_mesh_vtx_6[70];
extern Gfx lll_dl_skinned_mesh_tri_6[];
extern Vtx lll_dl_skinned_mesh_vtx_7[24];
extern Gfx lll_dl_skinned_mesh_tri_7[];
extern Vtx lll_dl_skinned_mesh_vtx_8[8];
extern Gfx lll_dl_skinned_mesh_tri_8[];
extern Vtx lll_dl_skinned_mesh_vtx_9[94];
extern Gfx lll_dl_skinned_mesh_tri_9[];
extern Vtx lll_dl_skinned_mesh_vtx_10[68];
extern Gfx lll_dl_skinned_mesh_tri_10[];
extern Vtx lll_dl_skinned_mesh_vtx_11[8];
extern Gfx lll_dl_skinned_mesh_tri_11[];
extern Vtx lll_dl_skinned_mesh_vtx_12[20];
extern Gfx lll_dl_skinned_mesh_tri_12[];
extern Vtx lll_dl_skinned_mesh_vtx_13[4];
extern Gfx lll_dl_skinned_mesh_tri_13[];
extern Vtx lll_dl_skinned_mesh_vtx_14[4];
extern Gfx lll_dl_skinned_mesh_tri_14[];
extern Vtx lll_dl_skinned_mesh_vtx_15[8];
extern Gfx lll_dl_skinned_mesh_tri_15[];
extern Vtx lll_dl_skinned_mesh_vtx_16[4];
extern Gfx lll_dl_skinned_mesh_tri_16[];

extern Gfx lll_dl_skinned_mesh[];
extern Gfx lll_dl_material_revert_render_settings[];

